name: publish

on:
  release:
    types: [published]

env:
  INTERPRETER_IMAGE: silvanmelchior/interpreter-venv
  OUTPUT_IMAGE: silvanmelchior/incognito-pilot
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies:
          - suffix: ""
            interpreter: 1.0.0
          - suffix: "-slim"
            interpreter: 1.0.0-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Get release type
        run: |
          VER=$(cat VERSION)
          if [[ $VER == *"b"* ]]; then
            echo "RELEASE_TYPE=nightly" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          file: docker/Dockerfile
          build-args: INTERPRETER_IMAGE=${{ env.INTERPRETER_IMAGE }}:${{ matrix.dependencies.interpreter }}
          push: true
          tags: |
            ${{ env.OUTPUT_IMAGE }}:${{ env.VERSION }}${{ matrix.dependencies.suffix }},
            ${{ env.OUTPUT_IMAGE }}:${{ env.RELEASE_TYPE }}${{ matrix.dependencies.suffix }}
